from typing import List
from pydantic import BaseModel, Field

class UploadResponse(BaseModel):
    """
    Data contract returned upon successful file upload and text extraction.
    """
    doc_id: str = Field(
        ..., 
        description="UUID reference assigned to the parsed document in backend cache."
    )
    filename: str = Field(
        ..., 
        description="The name of the file uploaded by the user."
    )
    char_count: int = Field(
        ..., 
        description="The total length of the raw text extracted from the document."
    )

class QueryRequest(BaseModel):
    """
    Data contract required to perform context-based Q&A query on a document.
    """
    doc_id: str = Field(
        ..., 
        description="Target document UUID reference."
    )
    question: str = Field(
        ..., 
        description="The natural language question to ask the AI assistant."
    )

class QueryResponse(BaseModel):
    """
    Response model containing the generated contextual answer.
    """
    answer: str = Field(
        ..., 
        description="The contextual response generated by the LLM based on document content."
    )

class InsightsResponse(BaseModel):
    """
    Structured schema representing business audits extracted directly from document text.
    Used for forcing JSON schemas on Gemini completions.
    """
    key_facts: List[str] = Field(
        ..., 
        description="Critical facts, core summaries, agreements, dates, or names extracted from the document."
    )
    important_numbers: List[str] = Field(
        ..., 
        description="Key financial metrics, values, counts, percentages, prices, or numeric data."
    )
    action_items: List[str] = Field(
        ..., 
        description="Actionable tasks, direct instructions, follow-up items, or recommendations for stakeholders."
    )
    risks: List[str] = Field(
        ..., 
        description="Warning signs, legal liabilities, anomalies, flagged concerns, or operational risks."
    )

class DocumentRequest(BaseModel):
    """
    General reference contract containing only a document's identifier.
    Used for compiling reports or triggering standalone operations.
    """
    doc_id: str = Field(
        ..., 
        description="Target document UUID reference."
    )

class ReportResponse(BaseModel):
    """
    Data contract returned when a summary report is compiled.
    """
    report: str = Field(
        ..., 
        description="The complete consultant summary report formatted in standard Markdown."
    )
